import Link from 'next/link';
import Image from 'next/image';
import {notFound} from 'next/navigation';
import {getLocale,dictionary,formatDate} from '@/lib/i18n';
import {pageMetadata} from '@/lib/metadata';
import {getBlogPost,listBlogPosts} from '@/lib/repository';
import {ArticleCards} from '@/components/public/content-cards';
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{locale:string;slug:string}>}){const {locale:raw,slug}=await params;const locale=getLocale(raw);const p=getBlogPost(slug,{publishedOnly:true});if(!p)return {};return {...pageMetadata(locale,`/blog/${slug}`,p.seoTitle[locale]||p.title[locale],p.seoDescription[locale]||p.excerpt[locale]),openGraph:{type:'article' as const,publishedTime:p.publishedAt||undefined,title:p.title[locale],description:p.excerpt[locale]}};}
export default async function Article({params}:{params:Promise<{locale:string;slug:string}>}){const {locale:raw,slug}=await params;const locale=getLocale(raw);const d=dictionary(locale);const p=getBlogPost(slug,{publishedOnly:true});if(!p)notFound();const structured={'@context':'https://schema.org','@type':'BlogPosting',headline:p.title[locale],description:p.excerpt[locale],datePublished:p.publishedAt,dateModified:p.updatedAt,author:{'@type':'Organization',name:p.author},inLanguage:locale};return <><article className="container narrow section"><div className="article-hero"><Link className="text-link back-link" href={`/${locale}/blog`}>{d.blog.back}</Link><div><span className="eyebrow">{p.category[locale]}</span></div><h1 style={{marginTop:24}}>{p.title[locale]}</h1><p style={{marginTop:24,fontSize:18}}>{p.excerpt[locale]}</p><div className="article-meta"><span>{d.blog.by} {p.author}</span><span>·</span><span>{formatDate(p.publishedAt||p.createdAt,locale)}</span></div></div>{p.cover&&<Image src={p.cover} alt={p.title[locale]} width={900} height={500} style={{borderRadius:20,marginBottom:30}}/>}<div className="prose">{p.content[locale].split('\n\n').filter(Boolean).map((paragraph,i)=>paragraph.startsWith('## ')?<h2 key={i}>{paragraph.slice(3)}</h2>:<p key={i}>{paragraph}</p>)}</div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,'\\u003c')}}/></article><section className="container section" style={{paddingTop:0}}><h2 style={{marginBottom:32}}>{d.blog.related}</h2><ArticleCards locale={locale} articles={listBlogPosts({publishedOnly:true}).filter(x=>x.id!==p.id).slice(0,3)}/></section></>}
