'use client';

import type { FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import type { Locale } from '@/lib/i18n';
import type { BlogPost } from '@/lib/domain';
import { dashboardMessages } from '@/content/dashboard-messages';
import { Field, MutationFeedback, SaveButton, useMutation } from './forms';

export function BlogEditor({ post, locale }: { post?: BlogPost; locale: Locale }) {
  const t = dashboardMessages(locale); const router = useRouter(); const mutation = useMutation(locale);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const body = { slug: data.get('slug'), title: { en: data.get('titleEn'), fa: data.get('titleFa') }, excerpt: { en: data.get('excerptEn'), fa: data.get('excerptFa') }, content: { en: data.get('contentEn'), fa: data.get('contentFa') }, category: { en: data.get('categoryEn'), fa: data.get('categoryFa') }, author: data.get('author'), cover: data.get('cover'), published: data.get('published') === 'on', seoTitle: { en: data.get('seoTitleEn') || data.get('titleEn'), fa: data.get('seoTitleFa') || data.get('titleFa') }, seoDescription: { en: data.get('seoDescriptionEn') || data.get('excerptEn'), fa: data.get('seoDescriptionFa') || data.get('excerptFa') } }; const ok = await mutation.mutate(post ? `/api/admin/blog/${post.id}` : '/api/admin/blog', body, post ? 'PATCH' : 'POST'); if (ok && !post) router.push(`/${locale}/admin/blog`); }
  async function remove() { if (!post || !window.confirm(t.deleteConfirm)) return; if (await mutation.mutate(`/api/admin/blog/${post.id}`, undefined, 'DELETE')) router.push(`/${locale}/admin/blog`); }
  return <form onSubmit={submit} className="workspace-form"><div className="workspace-form-grid"><Field label={t.titleEn}><input required name="titleEn" maxLength={200} defaultValue={post?.title.en} dir="ltr" /></Field><Field label={t.titleFa}><input required name="titleFa" maxLength={200} defaultValue={post?.title.fa} dir="rtl" /></Field><Field label={t.slug}><input required name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" minLength={3} maxLength={150} defaultValue={post?.slug} dir="ltr" /></Field><Field label={t.author}><input required name="author" maxLength={100} defaultValue={post?.author ?? 'Salsal Studio'} /></Field><Field label={t.excerptEn}><textarea required name="excerptEn" rows={3} maxLength={1000} defaultValue={post?.excerpt.en} dir="ltr" /></Field><Field label={t.excerptFa}><textarea required name="excerptFa" rows={3} maxLength={1000} defaultValue={post?.excerpt.fa} dir="rtl" /></Field><Field label={t.contentEn}><textarea required name="contentEn" rows={14} maxLength={20000} defaultValue={post?.content.en} dir="ltr" /></Field><Field label={t.contentFa}><textarea required name="contentFa" rows={14} maxLength={20000} defaultValue={post?.content.fa} dir="rtl" /></Field><Field label={t.categoryEn}><input required name="categoryEn" maxLength={100} defaultValue={post?.category.en} dir="ltr" /></Field><Field label={t.categoryFa}><input required name="categoryFa" maxLength={100} defaultValue={post?.category.fa} dir="rtl" /></Field><Field label={t.cover}><input name="cover" maxLength={300} defaultValue={post?.cover} placeholder="/images/article.webp" dir="ltr" /></Field><Field label={t.seoTitleEn}><input name="seoTitleEn" maxLength={200} defaultValue={post?.seoTitle.en} dir="ltr" /></Field><Field label={t.seoTitleFa}><input name="seoTitleFa" maxLength={200} defaultValue={post?.seoTitle.fa} dir="rtl" /></Field><Field label={t.seoDescriptionEn}><textarea name="seoDescriptionEn" rows={2} maxLength={500} defaultValue={post?.seoDescription.en} dir="ltr" /></Field><Field label={t.seoDescriptionFa}><textarea name="seoDescriptionFa" rows={2} maxLength={500} defaultValue={post?.seoDescription.fa} dir="rtl" /></Field></div><label className="workspace-checkbox"><input name="published" type="checkbox" defaultChecked={post?.published ?? false} /><span>{t.publish}</span></label><MutationFeedback feedback={mutation.feedback} /><div className="workspace-form-actions"><SaveButton pending={mutation.pending} locale={locale}>{post ? t.save : t.createArticle}</SaveButton>{post && <button type="button" className="workspace-button danger" onClick={remove} disabled={mutation.pending}>{t.delete}</button>}</div></form>;
}
